[build]
  publish = "."
  command = "echo 'No build step required'"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity"
  status = 200

[[redirects]]
  from = "/.netlify/git/*"
  to = "/.netlify/git"
  status = 200

[build.environment]
  NODE_VERSION = "18"
