[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Visual Editor Configuration
[context.production.environment]
  NETLIFY_CMS_BACKEND = "git-gateway"
  NETLIFY_CMS_PREVIEW_PATH = "/"