backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  # Site Settings
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "content/settings/general.json"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Description", name: "site_description", widget: "text"}
          - {label: "Brand Name", name: "brand_name", widget: "string"}
          - {label: "Contact Email", name: "contact_email", widget: "string"}
          - {label: "Contact Phone", name: "contact_phone", widget: "string"}
          - {label: "Contact Address", name: "contact_address", widget: "text"}

      - label: "Hero Section"
        name: "hero"
        file: "content/settings/hero.json"
        fields:
          - {label: "Badge Text", name: "hero_badge", widget: "string"}
          - {label: "Main Title", name: "hero_title", widget: "string"}
          - {label: "Subtitle", name: "hero_subtitle", widget: "text"}
          - {label: "Booking Button Text", name: "booking_button_text", widget: "string"}
          - {label: "Booking URL", name: "booking_url", widget: "string"}
          - {label: "Services Button Text", name: "services_button_text", widget: "string"}
          - {label: "Quote", name: "hero_quote", widget: "text"}
          - {label: "Quote Author", name: "hero_quote_author", widget: "string"}

      - label: "Team Section"
        name: "team"
        file: "content/settings/team.json"
        fields:
          - {label: "Section Badge", name: "team_badge", widget: "string"}
          - {label: "Section Title", name: "team_title", widget: "string"}
          - {label: "Section Subtitle", name: "team_subtitle", widget: "text"}
          - label: "Team Member 1"
            name: "team_member_1"
            widget: "object"
            fields:
              - {label: "Name", name: "team_member_1_name", widget: "string"}
              - {label: "Title", name: "team_member_1_title", widget: "string"}
              - {label: "Description", name: "team_member_1_description", widget: "text"}
              - {label: "Booking Text", name: "team_member_1_booking_text", widget: "string"}
              - {label: "Booking URL", name: "team_member_1_booking_url", widget: "string"}
          - label: "Team Member 2"
            name: "team_member_2"
            widget: "object"
            fields:
              - {label: "Name", name: "team_member_2_name", widget: "string"}
              - {label: "Title", name: "team_member_2_title", widget: "string"}
              - {label: "Description", name: "team_member_2_description", widget: "text"}
              - {label: "Booking Text", name: "team_member_2_booking_text", widget: "string"}
              - {label: "Booking URL", name: "team_member_2_booking_url", widget: "string"}
          - label: "Team Member 3"
            name: "team_member_3"
            widget: "object"
            fields:
              - {label: "Name", name: "team_member_3_name", widget: "string"}
              - {label: "Title", name: "team_member_3_title", widget: "string"}
              - {label: "Description", name: "team_member_3_description", widget: "text"}
              - {label: "Booking Text", name: "team_member_3_booking_text", widget: "string"}
              - {label: "Booking URL", name: "team_member_3_booking_url", widget: "string"}

      - label: "Footer"
        name: "footer"
        file: "content/settings/footer.json"
        fields:
          - {label: "Brand Name", name: "footer_brand_name", widget: "string"}
          - {label: "Description", name: "footer_description", widget: "text"}